<<<<<<< HEAD
server.port=8080
server.address=0.0.0.0
app.cors.allowed-origin-patterns=http://localhost:*,http://127.0.0.1:*,https://*.ngrok-free.app,https://*.ngrok-free.dev,https://*.ngrok.io,https://*.ngrok.app,https://*.ngrok.dev
spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca
=======
spring.datasource.url=jdbc:postgresql://localhost:5432/BIBLIOTECA_BD
>>>>>>> f1c942b357e26ea8407126567397b833e9cf7c6f
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.connection-init-sql=SET bytea_output = 'escape'